### PR TITLE
Fix duplicate overload

### PR DESCRIPTION
**Pull request by uWynell**
There were 2 identical overloads for 1 method and I removed one

### CODE REVIEW

**Comment by uWynell** [comment]
They are the identical, why tests are failing!?

**Comment by wojpawlik** [comment]
https://www.typescriptlang.org/docs/handbook/functions.html#overloads

**Comment by uWynell** [comment]
> https://www.typescriptlang.org/docs/handbook/functions.html#overloads
Why there are **two absolutely identical** overloads?

**Comment by wojpawlik** [comment]
The second one is not an overload. It's an _internal_ signature, not exposed to callers by default.

**Comment by uWynell** [comment]
> The second one is not an overload. It's an _internal_ signature, not exposed to callers by default.
where can I read about it?

**Pull request closed without merging**
