### PR TITLE
feat(client): add timeout option

### PR DESCRIPTION
**Pull request by Morb0**
# Description

With the current constant timeout impossible to upload big files.

## Type of change
- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by wojpawlik** [comment]
I'd rather not, `node-fetch@3` drops `timeout` entirely: https://github.com/node-fetch/node-fetch/issues/523

**Comment by wojpawlik** [comment]
[Transforming timeout into signal](https://github.com/node-fetch/timeout-signal) when needed is straightforward. However, [combining signals](https://github.com/jacobheun/any-signal) is not. Alternative (in `node-fetch@3`) is to drop the timeout when `signal` is passed, which [defeats the point](https://github.com/telegraf/telegraf/pull/1224#issuecomment-742820310).

How about we just drop the fetch timeout entirely for now, and rely only on existing [`handlerTimeout`](https://telegraf.js.org/interfaces/telegraf.options.html#handlertimeout), @KnorpelSenf?

**Comment by KnorpelSenf** [comment]
Go ahead, I will keep myself out of the discussion around timeouts (and update handling). It's OK if you skip tagging me

**Comment by wojpawlik** [comment]
I'll do that then. API calls could be aborted after `handlerTimeout`... but that's a separate discussion.

**Pull request closed without merging**
