### PR TITLE
Fix AWS Lambda deployment error

### PR DESCRIPTION
**Pull request by TrueCarry**
For some reason Lambda Node.JS(v6.10) doesn't support 'in' operator. Changed it for hasOwnProperty, so it works.

### CODE REVIEW

**Comment by dotcypress** [comment]
Hmm 😕 

@TrueCarry are you sure that node `v6.10.` doesn't support 'in' operator?

screen shot 2018-01-17 at 9 52 53 pm

**Comment by TrueCarry** [comment]
Sorry for the long response.
@dotcypress I'm sure that current AWS Lambda version throws on that line.

**Comment by TrueCarry** [comment]
Checked everything again. Worked this time.

**Comment by dotcypress** [comment]
Great. 
Closing for now

**Pull request closed without merging**
