### PR TITLE
fix: Fixed lint leading to broken build

### PR DESCRIPTION
**Pull request by atassis**
You have broken the build by this

### CODE REVIEW

**Review by MKRhere — APPROVED** [review]

**Comment by atassis** [comment]
Can you deploy this? It adds an ability to connect a test env, pretty useful

**Comment by atassis** [comment]
Can you deploy this? It adds an ability to connect a test env, pretty useful

**Comment by MKRhere** [comment]
Done, telegraf@4.8.2

**Comment by atassis** [comment]
Your deploy didn't happen, no 4.8.2
image

**Comment by MKRhere** [comment]
It's fixed

**Comment by MKRhere** [comment]
Takes some time for npm website to update, but you will be able to install it using `npm i telegraf@latest` or `npm i telegraf@4.8.2`

**Pull request merged**
