### PR TITLE
Cache `node_modules/` in CI

### PR DESCRIPTION
**Pull request by wojpawlik**
# Description

## Type of change

# How Has This Been Tested?

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by wojpawlik** [comment]
Caching `~/.npm` provides just <=1s speedup lol, suggesting that npm spends most time on disk IO, I don't think it's worth bothering. Perhaps caching `node_modules` could be faster, but [it's discouraged](https://github.com/actions/cache/blob/main/examples.md#node---npm).

I'll upgrade `actions/setup-node` to `v2` next time I touch the file, it shaves off 2 seconds with no extra code.

**Comment by wojpawlik** [comment]
I'll try caching `node_modules/` instead, but only if `package-lock.json` haven't changed and Node versions match.

**Comment by wojpawlik** [comment]
Bringing `node_modules/` from cache takes just 3 seconds. It's done only if Node version and hash of `package-lock.json` match. Otherwise a fresh `npm ci --ignore-scripts` is performed, without any caching, which takes 6 to 9 seconds.

**Comment by wojpawlik** [comment]
If this works well, I'll encapsulate it in a GitHub Action for easier reuse. If it does not, I'll revert it.

**Comment by KnorpelSenf** [comment]
Not quite sure which problem this PR solves. If it's just regular config maintenance (upgrading tooling), then sure, go ahead. It seems like you're trying to make CI faster, though. Does this matter? Caching files ignored by git `node_modules` really is not a good idea. There should be a very strong point why another setup is not possible before you buy in a new class of problems.

**Comment by wojpawlik** [comment]
Faster CI improves contributor experience, and incentivizes parallelizing the checks.

Why is caching `node_modules/` a bad idea?

I couldn't find a better way, aside from switching package manager, which would be much more disruptive.

**Comment by KnorpelSenf** [comment]
> Why is caching `node_modules/` a bad idea?

Because you by definition have no reproducibility of the builds anymore. If something breaks, it takes a lot of effort to guarantee that the problem is not related to caching. (You may be familiar with https://shouldiblamecaching.com/). Having CI build from scratch is super nice and makes you sleep well at night.

**Comment by wojpawlik** [comment]
I find issues unlikely, I am defensive with cache key: https://github.com/telegraf/telegraf/blob/f4a30fdbd0efb3b973eada3c124662dca78450ea/.github/workflows/node.js.yml#L32

So I'm willing to take this risk. And to deal with any consequences that may arise, and learn from the experience.

**Pull request merged**
