### PR TITLE
chore: update agent typing

### PR DESCRIPTION
**Pull request by septs**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Documentation (typos, code examples or any documentation update)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Node.js Version:
* Operating System:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by septs** [comment]
Update 3.38.0 typing, fix 3.38.0 incorrect typing.

CC @KnorpelSenf

**Comment by wojpawlik** [comment]
Hold on. This targets `master`, not `develop`. It's not up to @KnorpelSenf, it's up to @dotcypress (good luck)!

**Comment by septs** [comment]
> @septs did you mean to target `develop` instead of `master`?

fix my workaround need `@ts-ignore`

see https://github.com/telegraf/telegraf/issues/814#issuecomment-739501639

**Comment by wojpawlik** [comment]
I don't think it's worth revisiting this version just to fix a `// @ts-ignore` in your code. Feel free to reopen @dotcypress if you see this and disagree.

You should do your best to write a issue comment next time @septs, you can improve your English by practicing.

**Pull request closed without merging**
