### PR TITLE
Publish `declarationMap`

### PR DESCRIPTION
**Pull request by septs**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Documentation (typos, code examples or any documentation update)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Node.js Version:
* Operating System:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by wojpawlik — CHANGES_REQUESTED** [review]
What's the point if source maps and `src/` aren't published to npm? https://github.com/telegraf/telegraf/blob/1f7dee72c702bdf05791ccba2a8a8c3b3c6f9dfc/package.json#L20-L25

Personally, I'm not a fan of wasting space by publishing unnecessary files to npm.

**Comment by septs** [comment]
> Enabling --declarationMap alongside --declaration causes the compiler to emit .d.ts.map files alongside the output .d.ts files. Language Services can also now understand these map files, and uses them to map declaration-file based definition locations to their original source, when available.

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#new---declarationmap

**Comment by septs** [comment]
```
$ npm publish --dry-run

> telegraf@3.38.0 prepare .
> npm run build && mjs-entry src/index.ts > lib/index.mjs


> telegraf@3.38.0 build /Users/septs/Projects/NiceLabs/telegraf
> tsc --build docs/examples

npm notice
npm notice 📦  telegraf@3.38.0
npm notice === Tarball Contents ===
npm notice 1.1kB  LICENSE
npm notice 2.0kB  bin/telegraf
npm notice 1.3kB  lib/scenes/base.js
npm notice 1.7kB  lib/button.js
npm notice 1.6kB  lib/core/helpers/check.js
npm notice 11.0kB lib/core/network/client.js
npm notice 16.1kB lib/composer.js
npm notice 18.4kB lib/context.js
npm notice 2.8kB  lib/scenes/context.js
npm notice 630B   lib/scenes/wizard/context.js
npm notice 412B   lib/core/network/error.js
npm notice 2.7kB  lib/extra.js
npm notice 3.4kB  lib/core/helpers/formatting.js
npm notice 2.4kB  lib/index.js
npm notice 1.7kB  lib/scenes/wizard/index.js
npm notice 3.2kB  lib/markup.js
npm notice 1.3kB  lib/core/network/multipart-stream.js
npm notice 5.0kB  lib/core/replicators.js
npm notice 1.6kB  lib/router.js
npm notice 913B   lib/session.js
npm notice 1.8kB  lib/stage.js
npm notice 9.3kB  lib/telegraf.js
npm notice 1.0kB  lib/telegram-types.js
npm notice 34.0kB lib/telegram.js
npm notice 125B   lib/types.js
npm notice 1.4kB  lib/core/network/webhook.js
npm notice 2.3kB  package.json
npm notice 951B   typings/scenes/base.d.ts.map
npm notice 1.2kB  lib/scenes/base.js.map
npm notice 1.5kB  typings/button.d.ts.map
npm notice 1.6kB  lib/button.js.map
npm notice 940B   typings/core/helpers/check.d.ts.map
npm notice 578B   lib/core/helpers/check.js.map
npm notice 907B   typings/core/network/client.d.ts.map
npm notice 9.1kB  lib/core/network/client.js.map
npm notice 7.5kB  typings/composer.d.ts.map
npm notice 16.2kB lib/composer.js.map
npm notice 5.1kB  typings/context.d.ts.map
npm notice 970B   typings/scenes/context.d.ts.map
npm notice 821B   typings/scenes/wizard/context.d.ts.map
npm notice 17.7kB lib/context.js.map
npm notice 2.7kB  lib/scenes/context.js.map
npm notice 826B   lib/scenes/wizard/context.js.map
npm notice 441B   typings/core/network/error.d.ts.map
npm notice 485B   lib/core/network/error.js.map
npm notice 1.3kB  typings/extra.d.ts.map
npm notice 2.2kB  lib/extra.js.map
npm notice 239B   typings/core/helpers/formatting.d.ts.map
npm notice 2.8kB  lib/core/helpers/formatting.js.map
npm notice 509B   typings/index.d.ts.map
npm notice 929B   typings/scenes/wizard/index.d.ts.map
npm notice 413B   lib/index.js.map
npm notice 1.6kB  lib/scenes/wizard/index.js.map
npm notice 1.5kB  typings/markup.d.ts.map
npm notice 2.2kB  lib/markup.js.map
npm notice 536B   typings/core/network/multipart-stream.d.ts.map
npm notice 1.1kB  lib/core/network/multipart-stream.js.map
npm notice 1.5kB  typings/core/replicators.d.ts.map
npm notice 4.0kB  lib/core/replicators.js.map
npm notice 792B   typings/router.d.ts.map
npm notice 1.3kB  lib/router.js.map
npm notice 397B   typings/session.d.ts.map
npm notice 1.1kB  lib/session.js.map
npm notice 1.0kB  typings/stage.d.ts.map
npm notice 1.7kB  lib/stage.js.map
npm notice 2.0kB  typings/telegraf.d.ts.map
npm notice 7.5kB  lib/telegraf.js.map
npm notice 4.8kB  typings/telegram-types.d.ts.map
npm notice 231B   lib/telegram-types.js.map
npm notice 8.2kB  typings/telegram.d.ts.map
npm notice 13.9kB lib/telegram.js.map
npm notice 1.0kB  typings/types.d.ts.map
npm notice 112B   lib/types.js.map
npm notice 351B   typings/core/network/webhook.d.ts.map
npm notice 1.4kB  lib/core/network/webhook.js.map
npm notice 2.7kB  readme.md
npm notice 459B   lib/index.mjs
npm notice 918B   typings/scenes/base.d.ts
npm notice 1.6kB  typings/button.d.ts
npm notice 1.7kB  typings/core/helpers/check.d.ts
npm notice 806B   typings/core/network/client.d.ts
npm notice 9.1kB  typings/composer.d.ts
npm notice 14.7kB typings/context.d.ts
npm notice 1.0kB  typings/scenes/context.d.ts
npm notice 843B   typings/scenes/wizard/context.d.ts
npm notice 364B   typings/core/network/error.d.ts
npm notice 2.2kB  typings/extra.d.ts
npm notice 181B   typings/core/helpers/formatting.d.ts
npm notice 419B   typings/index.d.ts
npm notice 859B   typings/scenes/wizard/index.d.ts
npm notice 1.6kB  typings/markup.d.ts
npm notice 502B   typings/core/network/multipart-stream.d.ts
npm notice 1.8kB  typings/core/replicators.d.ts
npm notice 821B   typings/router.d.ts
npm notice 473B   typings/session.d.ts
npm notice 1.0kB  typings/stage.d.ts
npm notice 2.6kB  typings/telegraf.d.ts
npm notice 7.7kB  typings/telegram-types.d.ts
npm notice 29.2kB typings/telegram.d.ts
npm notice 880B   typings/types.d.ts
npm notice 393B   typings/core/network/webhook.d.ts
npm notice === Tarball Details ===
npm notice name:          telegraf
npm notice version:       3.38.0
npm notice package size:  69.5 kB
npm notice unpacked size: 350.6 kB
npm notice shasum:        b46efef7217a2edf3923844b090af7895a1fa35d
npm notice integrity:     sha512-/Bwr8Cv10XPz9[...]pF0xJSZd9RlFw==
npm notice total files:   101
npm notice
+ telegraf@3.38.0
```

@wojpawlik fixed.

**Comment by wojpawlik** [comment]
I don't like the idea of doubling package size just to improve <kbd>F12</kbd>... What about you @KnorpelSenf? Current `develop`:

```
~/JS/telegraf (develop $=)
$ npm pack

# -- snip --
npm notice === Tarball Details ===
npm notice name:          telegraf
npm notice version:       3.38.0
npm notice filename:      telegraf-3.38.0.tgz
npm notice package size:  43.7 kB
npm notice unpacked size: 217.0 kB
npm notice shasum:        754675e0c40296c2884373d2c3d27de94d78b17f
npm notice integrity:     sha512-NpMtsHs7XDcsz[...]icDEbJKC8jWyQ==
npm notice total files:   53
npm notice
telegraf-3.38.0.tgz
```

**Comment by septs** [comment]
1. This is server-side library
2. Provide source map, can directly see how it is works.

**Review by wojpawlik — COMMENTED** [review]
I understand that `declarationMap` helps with "Go to definition" (<kbd>F12</kbd>), but what does `sourceMap` (92.9 kB / 16.9 kB gzipped) give us here?

**Comment by KnorpelSenf** [comment]
> 1. This is server-side library

This.

I do care a lot about the number of files that are required to _run_ the framework. I care about startup time, and about the performance of an architecture. On the other hand, I must say that I never found the size of `node_modules` too important.

We added 200+ kB in TypeScript annotations to improve the development experience. I find it okay to do that again.

**Comment by KnorpelSenf** [comment]
We can actually send a poll in the group chat about that. That's something where people actually can have qualified opinions without knowing any internals.

**Comment by AndrewLaneX** [comment]
Poll: https://t.me/TelegrafJSChat/12323

**Review by wojpawlik — APPROVED** [review]
Feel free to open a new PR if you have a good reason to want to build and perhaps publish source maps.

**Pull request merged**
