### PR TITLE
Clear updates

### LINKED ISSUE #454: Possibility to clear update queue when starting the bot
It is sometimes desirable to ignore all updates a bot has received since it was last shut down. There is a way to *almost*  do this: `bot.polling.offset = -1;`, which deletes all except the last update. Setting it to `-0` does not work.

An option `bot.startPolling({clearQueue: true});` would be nice. Or `bot.clearUpdates();`

I've had this in one of my bots which is currently using a thin API wrapper, and which I'm currently converting to use Telegraf. The way I did it there was to have a function which repeatedly does `bot.getUpdates` with a timeout of 0, getting the ID of the last update in the resulting array to use as offset, until receiving an empty update array from Telegram. It then returns the offset to use. [See this implementation](https://github.com/TediCross/TediCross/blob/21e5eed5d1a28557e6549a44e4e4181d36257497/lib/telegram2discord/makeUpdateEmitter.js#L31). Starting with initial offset -1 instead of 0 will make just one call to `getUpdates` necessary.

If I had access to the `bot.telegram.getUpdates` method on the Telegraf bot, I could boilerplate it myself, but that method appears to be hidden in Telegraf.

### PR DESCRIPTION
**Pull request by Suppen**
# Description

Added a method `telegram.clearUpdates` which clears the update queue of the bot. Useful to ignore old messages when starting the bot

Fixes #454 

## Type of change

- [X] Documentation (typos, code examples or any documentation update)
- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

# How Has This Been Tested?

- [X] Tests pass
- [X] Linter has no complaints
- [X] Tested on a bot, both before and after starting to poll. Works as expected
- [ ] Tested with webhooks. Expected to work when no webhook is in place, and fail when there is one, but I have not tested

**Test Configuration**:
* Node.js Version: 8.11.3
* Operating System: Kubuntu 18.04

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by dotcypress** [comment]
@Suppen thank you for PR, but I can't merge it. Clearing user messages isn't a good practice, cause any information is important. I understood the pros of this approach in debug mode, and will be great to have such feature as external Telegraf middleware. 

For example: 
```js
const { drop } = require('telegraf')

// Uncomment next line and start bot to clear all updates
// bot.drop((ctx) => true)

bot.start((ctx) => {})
```

**Comment by trgwii** [comment]
I would say that what information is important is up to each specific bot to decide... There are valid use cases for this!

**Comment by Suppen** [comment]
It's up to you to decide what to merge, but I don't agree with your reasoning. It is completely up to the user to decide whether or not to use the method. It is not being forced in any way

**Comment by Pumych** [comment]
Sorry to hear that this commit is not merged. It is really required one, I prefer to miss some data than to have the bot banned.
Is there a way to add this code in other way?

**Comment by wojpawlik** [comment]
```ts
bot.launch({ dropPendingUpdates: true })
```

**Pull request closed without merging**
