### PR TITLE
Add AWS Lambda Example Code

### PR DESCRIPTION
**Pull request by septs**
# Description

Add AWS Lambda Example code

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by nezort11** [comment]
@septs  @KnorpelSenf  , am I right that in order for `sendChatAction` (with `replyToWebhook`) work in serverless environment (Lambda, Google functions, etc.) i need to add `webhookReply: false` ?

**Comment by KnorpelSenf** [comment]
Yes. In fact, if you ever want to perform two API calls for the same incoming request (no matter if you call `sendChatAction` or something else) then you must disable webhook reply that way. 

This is because AWS doesn't allow your code to run after the request was completed by sending a response.

Moreover, note that this means that the request will likely take a few seconds until it is completed. That is acceptable for very small bots with just a few hundred users, but it leads to drastic performance problems for all larger projects. Telegram only ever sends up to 100 updates in parallel so if each of them takes 10 seconds to process, your throughput will drop to 10 messages/second.

Finally, if your requests take even longer than that, your bot may receive the same updates many times, which leads to an entirely new type of problem. I explained it in depth here: https://grammy.dev/guide/deployment-types#ending-webhook-requests-in-time (I don't think telegraf has docs for this)

**Comment by KnorpelSenf** [comment]
Not all serverless environments work that way btw, but AWS does

**Comment by nezort11** [comment]
Thanks a lot for the clarifications.

**Pull request merged**
