### PR TITLE
Add MarkdownV2 to Extras

### PR DESCRIPTION
**Pull request by Ashesh3**
# Description

This adds MarkdownV2 to telegraf/extras

## Type of change
Currently only `Extra.markdown()` is possible, there's no direct support for MarkdownV2 in Extras

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tried sending a message with `MarkdownV2` parse_mode and can confirm i can use all basic markdown plus nested markdown too (only a feature of v2)
image

**Test Configuration**:
* Node.js Version: v14.1.0
* Operating System: Windows 10 x64

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Loskir** [comment]
Typings would be nice to have

**Comment by Loskir** [comment]
Also I don't really like `markdownv2` name, but can't come up with better ideas (`MarkdownV2` maybe, but I don't like it either)

**Comment by wojpawlik** [comment]
`markdownV2`, for consistency? https://github.com/telegraf/telegraf/blob/cce84b355d80363c3620f3283d7f66558d08b201/context.js#L561

**Comment by Ashesh3** [comment]
> `markdownV2`, for consistency?
> 
> https://github.com/telegraf/telegraf/blob/cce84b355d80363c3620f3283d7f66558d08b201/context.js#L561

Hey, it is already 'markdownV2' as you can see [here](https://github.com/telegraf/telegraf/pull/1060/commits/878b95217d61183fdfd094b22660ef1e7e755537)
What is pending to get it out of the draft? :)

**Comment by wojpawlik** [comment]
I mean, "v" should be upper case. I don't see this PR getting out of draft state, I think it should be redone after #1076.

**Comment by KnorpelSenf** [comment]
@Ashesh3 that is a good idea, check out https://github.com/telegraf/telegraf/blob/develop/src/extra.ts and reapply your changes there. The newly added dependency to [typegram](https://www.npmjs.com/package/typegram) already makes sure that `'MarkdownV2'` is a permitted value for `parse_mode` and it would make sense if `telegraf` had support for that.

**Pull request closed without merging**
