### PR TITLE
added a subscription to a single event

### PR DESCRIPTION
**Pull request by Defenderbass**

### CODE REVIEW

**Comment by dotcypress** [comment]
Hey.

Thank you for your time!

Afraid i can't merge this PR, because you trying to save bot state only in memory.
With this approach you can't restart bot without losing bot state.

But you can easily extract this code to separated package.

BTW: If you want, i can create new repo for you in Telegraf org.

**Comment by Defenderbass** [comment]
Thank you, I will be happy!

**Comment by dotcypress** [comment]
@Defenderbass please choose repo name ;)

**Comment by Defenderbass** [comment]
Can be modified-telegraf?:smirk:

**Comment by dotcypress** [comment]
i mean name for separated package, like `telegraf-once`

**Comment by Defenderbass** [comment]
@dotcypress so let it be telegrah-once. I like

**Comment by dotcypress** [comment]
Done!
https://github.com/telegraf/telegraf-once

**Pull request closed without merging**
