### PR TITLE
Adding Markup support to TS typings and some other things.

### PR DESCRIPTION
**Pull request by Fazendaaa**
# Description

Just improving TypeScript typings:
* Adding Markup class support
* Correcting answerCallbackQuery to answerCbQuery and adding catch support

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

No testing implemented

# Checklist:

- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by Piterden** [comment]
This file is generated on a fly, you should edit telegram-typings package...

**Comment by Fazendaaa** [comment]
@Piterden , do you know how can I make typings for Stage support? I'm having a little bit of trouble with that right now.

**Comment by Piterden** [comment]
@Fazendaaa don't understand what you mean. Could you explain more detailed?

**Comment by Fazendaaa** [comment]
@Piterden right now, I've my TS project and trying to do the following [Stage](https://telegraf.js.org/#/?id=stage) example and failing because of the used types are not defined -- which is ok.

My doubt is "how can I make the used types since is a submodule dependency?". I just don't know the procedure, but I'm willing to make it once I learn it.

Do you know how can I make it? Is there anywhere a example?

**Comment by lenovouser** [comment]
@Piterden are you sure this is generated on the fly? `Markup` for example comes from [`telegraf/markup.js`](https://github.com/telegraf/telegraf/blob/develop/markup.js) which is custom to this module. So his change seems right to me?

**Comment by lenovouser** [comment]
@Piterden `telegram-typings` are the typings for the responses that Telegram gives us over the network. These typings here are something different / for the node module - so what @Fazendaaa did is correct and can be merged as soon as he rebases in my opinion.

**Comment by Piterden** [comment]
@lenovouser got it. Sorry, I was confused and hurried up a bit... Anyway, TT needs to be rewritten.

**Pull request merged**
