### PR TITLE
Added return of an object describing the connection result.

### PR DESCRIPTION
**Pull request by an-ivannikov**
# Description

Added return of an object describing the connection result.

## Type of change

Please delete options that are not relevant.

- [ ] Documentation (typos, code examples or any documentation update)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Node.js Version:
* Operating System:

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by an-ivannikov** [comment]
Честно я не понимаю зачем вы это сделали:
https://github.com/telegraf/telegraf/pull/1004

Когда я предлагал и говорил совсем о другом: о том чтобы возвращать ответ с описанием. сейчас ничего не возвращается. и вы убрали перехват ошибки. Не понимаю.

**Comment by an-ivannikov** [comment]
это например 
```js
      .catch((err) => {
        console.error('Launch failed')
        console.error(err.stack || err.toString())
        return { ok: false, error: { message: 'Launch failed', code: err.code ? err.code : null } }
      })
```
можно заменить на выражение с 'throw'
```js
      .catch((err) => {
        console.error('Launch failed')
        console.error(err.stack || err.toString())
        throw new Error({ ok: false, error: { message: 'Launch failed', code: err.code ? err.code : null } })
      })
```

**Comment by wojpawlik** [comment]
What's the pragmatic advantage over current code?

**Comment by an-ivannikov** [comment]
This code exposes the object describing the result of the connections. You can specify an error code in it, they are different for the state when there is no connection and when the server rejects the connection.

Nothing is returned in the current code. if successful, returns 'undefined'.

to your code in case of an error also returned 'undefined'.

After your code, the program will simply crash if an error is not caught.

**Comment by an-ivannikov** [comment]
Your code was created in a simple way - just delete what bothers you. On the contrary, I expanded the functionality of the code.

**Comment by wojpawlik** [comment]
Crashing is the correct thing to do if error is not handled, isn't it?

> to your code in case of an error also returned 'undefined'.

Not true, it idiomatically returns rejected promise with an error.

**Comment by an-ivannikov** [comment]
`to your code ...` -> before your code ...

**Comment by wojpawlik** [comment]
I fail to see how any `.catch` can be beneficial here

**Comment by an-ivannikov** [comment]
Any `.catch` can be useful here for working out errors at the framework level. In my code, there is also a `throw new Error` which will nullify the presence of `.catch`.

**Comment by wojpawlik** [comment]
How is "Launch failed" any more helpful than, well, any error returned from `.launch`?

**Comment by an-ivannikov** [comment]
The framework handles the error and throws a new exception. Processing at the framework level can be any.

It is important for me to get an error code so that I can understand the reason: the network is not working or is it a connection problem associated with blocking telegram servers in Russia.

At the moment, the framework does not return anything if successful. The fremvor returned nothing to your code in case of an error. The framework intercepted the event, wrote to the console about the presence of an error, but did not return the error and the object.

My code suggestion makes the framework handle success and error but always returns a correct description.

**Comment by wojpawlik** [comment]
I wouldn't oppose returning something useful on success.
However, I don't think that any error processing is currently necessary.

> It is important for me to get an error code so that I can understand the reason

`.catch(({ code }) => {...})` should work currently.

**Comment by an-ivannikov** [comment]
I wouldn't oppose returning something useful on success.
However, I don't think that any error processing is currently necessary.

I do not agree with you. I believe that starting a bot should return the result anyway.

This code is currently working. I know this without you. Prior to your code changes (removing interception) this could not work.

In any case, I do not care because I use a post-installed script to replace your file with my file with my changes.

If you think that it will be better for your project not to return the result of the action, then this is your problem. You can break the whole project into electronic functions and each user will have to create his own framework.

I will just make my fork and will provide a convenient framework that works out of the box and in which each action returns a result.

Success in the development of the project. I'm tired of this useless conversation. You can continue to remove from the project those problem areas that you cannot solve.

**Pull request closed without merging**
