### PR TITLE
fix for Composer.command

### PR DESCRIPTION
**Pull request by Lisand7ru**
Hello. It's me again.

I just have found out that Composer.command accept any command that is containing in a message. That's not a right way.

Look at official bots - @botfather, @telegraph. They consider a text message as a command only if it starts with a command.

### CODE REVIEW

**Comment by dotcypress** [comment]
Hey
Makes sense.

**Comment by dotcypress** [comment]
@Lisand7ru please fix or delete failing test: https://github.com/telegraf/telegraf/blob/develop/test/composer.js#L469

**Comment by Lisand7ru** [comment]
Done

**Comment by dotcypress** [comment]
Published @ `3.8.2`

**Pull request merged**
